project:
  type: website

website:
  site-url: "https://questionable.quarto.pub/recipes/"
  title: "questionable.quarto"
  navbar:
    left:
      - text: "Home"
        href: https://questionable.quarto.pub/blog/
      - text: "Projects"
        icon: fa-database
        menu:
          - text: "Posts"
            href: https://questionable.quarto.pub/blog/posts.html
          - text: "Presentations"
            href: https://questionable.quarto.pub/blog/presentations.html
          - text: "Recipes"
            href: index.qmd
      - text: "Posts"
        href: https://questionable.quarto.pub/blog/posts.html
      - text: "Presentations"
        href: https://questionable.quarto.pub/blog/presentations.html
      - text: "Recipes"
        href: index.qmd

    right:
      - text: "About"
        href: https://questionable.quarto.pub/blog/about.html
      - text: "Site Map"
        href: https://questionable.quarto.pub/blog/site_map.html
      - icon: github
        href: https://github.com/leesahanders/my_website
format:
  html:
    theme: 
      light: custom_theme.scss
      dark: vapor
    css: styles.css

